### ISSUE TITLE
ping -I device_name device_ip_address (self) does not work

### ISSUE THREAD

**Issue by jsynacek** [iputils/iputils#104] opened 2017-10-11 08:39 UTC
It's a rather cosmetic issue, but still...
```
# ip addr show dev eth0 | grep inet
    inet 192.168.122.100/24 brd 192.168.122.255 scope global eth0
    inet6 fe80::8817:157e:68cc:d912/64 scope link 

# ping -I eth0 192.168.122.100
PING 192.168.122.100 (192.168.122.100) from 192.168.122.100 eth0: 56(84) bytes of data.
<nothing... loops forever>

# ping -I 192.168.122.100 192.168.122.100
PING 192.168.122.100 (192.168.122.100) from 192.168.122.100 : 56(84) bytes of data.
64 bytes from 192.168.122.100: icmp_seq=1 ttl=64 time=0.029 ms
64 bytes from 192.168.122.100: icmp_seq=2 ttl=64 time=0.048 ms
64 bytes from 192.168.122.100: icmp_seq=3 ttl=64 time=0.024 ms
<works just fine>
```
Note that using the device name when pinging the IP address of the same device results in ping not working, whereas using the device IP address instead of its name does work.

This is a result of https://github.com/iputils/iputils/pull/56. I didn't really find a problem with the code itself. The described problem seems to happen because of the `setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);` is called on the `sock->fd` in addition to the probe fd. I'm not sure if this is a problem in the kernel, or in iputils code, or it's simply not meant to be used like that.

**Comment by kerolasa** [comment] 2018-10-24 22:49
I guess cancelling socket option when it does not work is an option. See commit 4082ba9e780320e3c6e31a21c7d7ad164c229b5b.

**Comment by kerolasa** [comment] 2018-11-11 10:36
Merged: cc44f4c5c2e72f7aa833658a6978d924ff9e059d

**Comment by threexc** [comment] 2020-01-06 21:09
Hello,

I am encountering an issue similar to this using release s20190709, but with IPv6. I've confirmed that the packets are actually appearing on the loopback interface with tcpdump, and that specifying the device as e.g. ping -6 fe80::92e2:baff:fe08:3738%eth0 works, but ping -6 -I eth0 fe80::92e2:baff:fe08:3738 does not. Both ping options work for me on s20180629. I've also tried writing a patch similar to [cc44f4c](https://github.com/iputils/iputils/commit/cc44f4c5c2e72f7aa833658a6978d924ff9e059d), but it didn't affect the result.

Is there a known problem with this behavior for IPv6? I don't see a related open issue except maybe https://github.com/iputils/iputils/issues/198.

**Comment by yizhao1** [comment] 2020-01-20 08:33
Hi,

I found it doesn't work when net.ipv4.ping_group_range sysctl is enabled. Since systemd 243, the ping_group_range sysctl is enabled:

root@qemux86-64:~# cat /usr/lib/sysctl.d/50-default.conf | grep "ping_group_range"
-net.ipv4.ping_group_range = 0 2147483647
root@qemux86-64:~# 
root@qemux86-64:~# cat /proc/sys/net/ipv4/ping_group_range 
0       2147483647
root@qemux86-64:~# 

Then the ping program will create ping (icmp) socket rather than raw socket. However, it doesn't work with -I dev option:
root@qemux86-64:~# 
root@qemux86-64:~# cat /proc/sys/net/ipv4/ping_group_range 
0       2147483647
root@qemux86-64:~# 
root@qemux86-64:~# ping -6 -c3 -I eth0 fe80::5054:ff:fe12:3402
ping: Warning: source address might be selected on device other than: eth0
PING fe80::5054:ff:fe12:3402(fe80::5054:ff:fe12:3402) from :: eth0: 56 data bytes

^C
--- fe80::5054:ff:fe12:3402 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2028ms

root@qemux86-64:~# 

When I disabled the sysctl, it can work:
root@qemux86-64:~# sysctl -w "net.ipv4.ping_group_range=1 0"
net.ipv4.ping_group_range = 1 0
root@qemux86-64:~# 
root@qemux86-64:~# ping -6 -c3 -I eth0 fe80::5054:ff:fe12:3402
ping: Warning: source address might be selected on device other than: eth0
PING fe80::5054:ff:fe12:3402(fe80::5054:ff:fe12:3402) from :: eth0: 56 data bytes
64 bytes from fe80::5054:ff:fe12:3402%eth0: icmp_seq=1 ttl=64 time=0.035 ms
64 bytes from fe80::5054:ff:fe12:3402%eth0: icmp_seq=2 ttl=64 time=0.010 ms
64 bytes from fe80::5054:ff:fe12:3402%eth0: icmp_seq=3 ttl=64 time=0.010 ms

--- fe80::5054:ff:fe12:3402 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2061ms
rtt min/avg/max/mdev = 0.010/0.018/0.035/0.011 ms
root@qemux86-64:~#

**Comment by pevik** [comment] 2020-01-20 14:52
BTW kernel in v5.2 got related fix [19e4e768064a ipv4: Fix raw socket lookup for local traffic](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=19e4e768064a87b073a4b4c138b55db70e0cfb9f).

**Comment by ValZapod** [comment] 2020-01-26 12:17
@pevik Yes, I have kernel 5.4.8-1 (latest testing), 

`ping -I eth0 192.168.1.69`
indeed works.
As well as `ping -6 -I eth0 fe80::0`

You can close it, I think.

**Comment by ValZapod** [comment] 2020-01-26 12:34
@pevik And also this commit https://github.com/torvalds/linux/commit/38c73529de13e1e10914de7030b659a2f8b01c3b

**Comment by pevik** [comment] 2020-01-26 19:44
@ValZapod thanks! Yep, fix became a regression, how usual in kernel development.
I plan to have a look into the issue, if there is a way to fix ping with kernel without fix.

**Comment by ValZapod** [comment] 2020-01-27 06:42
@pevik It is not really a regression 

> was done only for the first
> lookup. Subsequent lookups in the while loop still use skb->dev->ifIndex

and as it happened between revision candidates of the same version... It does really metter.

**Comment by ValZapod** [comment] 2020-01-27 20:56
We have a big probem. In 5.5 kernel we can now have multiple names of a one interface AND its length is now not maximum 16, it is now maximum 256! Are we ready for that?

**Comment by pevik** [comment] 2020-01-27 21:57
I don't see [these changes](https://kernelnewbies.org/Linux_5.5#Networking) as a problem:
* size 256 length is definitely not a problem (`char *p, *addr = strdup(optarg);` handling `-I` in https://github.com/iputils/iputils/blob/master/ping/ping.c#L388). BTW: I'd expect something like `getconf ARG_MAX`, which is 2097152 on my system, would fail, but in the reality is a bit more than half: 

```
$ ping  8.8.8.8 -I $(printf 'x%.0s' {1..131610})
bash: /bin/ping: Argument list too long

$ ping  8.8.8.8 -I $(printf 'x%.0s' {1..130610})
... xxxxxxxxxxxxxxxxxxxxxxxxxxxx: No such device
```
* What could cause troubles on interface being addressed by more names?

=> remember, Linux cares a lot on compatibility with user space.

**Comment by ValZapod** [comment] 2020-01-27 22:09
@pevik I am not a kernel programmer. Did you try 5.5 kernel? ;)

**Comment by ValZapod** [comment] 2020-04-21 00:49
Yes, it is indeed not a problem. Lets close it. Finally. 
"way to fix ping with kernel without fix"
No point I think. As the commit message mentions https://github.com/torvalds/linux/commit/19e4e768064a87b073a4b4c138b55db70e0cfb9f

```
As it stands, ping to a local address with the '-I <dev>' option fails
ever since ping was changed to use SO_BINDTODEVICE instead of
cmsg + IP_PKTINFO.
```
So if they say there is no way ;)

**Closed** 2020-09-17 21:13 UTC
