### ISSUE TITLE
ping: socket: Address family not supported by protocol

### ISSUE THREAD

**Issue by lekto** [iputils/iputils#293] opened 2020-09-02 19:31 UTC
Hi, I got message "ping: socket: Address family not supported by protocol" when using ping without "-4" after update to s20200821.
```
lekto@blaszak ~ $ ping github.com
ping: socket: Address family not supported by protocol
PING github.com (140.82.121.3) 56(84) bytes of data.
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=1 ttl=50 time=19.5 ms
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=2 ttl=50 time=18.7 ms
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=3 ttl=50 time=18.3 ms
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=4 ttl=50 time=17.8 ms
^C
--- github.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 17.818/18.561/19.457/0.601 ms

lekto@blaszak ~ $ ping -4 github.com
PING github.com (140.82.121.3) 56(84) bytes of data.
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=1 ttl=50 time=19.4 ms
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=2 ttl=50 time=18.2 ms
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=3 ttl=50 time=27.6 ms
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=4 ttl=50 time=18.7 ms
^C
--- github.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 18.240/20.992/27.623/3.852 ms
```

I did git bisect and it's showing me that this commit is causing this:
```
904cdb6dc9bd511847e31689873f9c57172f6b8d is the first bad commit
commit 904cdb6dc9bd511847e31689873f9c57172f6b8d
Author: Sami Kerola <kerolasa@iki.fi>
Date:   Sat Nov 30 19:14:39 2019 +0000

    ping: AF_INET6 is address family not socket type [lgtm scan]
    
    The lgtm scan gave rather strange warning 'Comparison is always false
    because socktype <= 3.' at this point in code.  Looking a little bit closer
    to issue I realized wrong variable was compared.  This seems to have slipped
    into ping five releases ago.
    
    Broken-since: d141cb6e4ee3388f0508afa0f6368aaa1236778c
    Signed-off-by: Sami Kerola <kerolasa@iki.fi>

 ping/ping.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

I'm using kernel without IPv6 support.

**Comment by pevik** [comment] 2020-09-02 19:57
Thanks for your report. The commit is correct. But is there a regression? I don't thing so, but code could be improved.

* For `-4` ping creates only `AF_INET` socket.
* For `-6` ping creates only`AF_INET6` socket.
* For the default (`AF_UNSPEC`) ping creates both AF_INET` and`AF_INET6` socket.

https://github.com/iputils/iputils/blob/4fd276cd8211c502cb87c5db0ce15cd685177216/ping/ping.c#L523-L533

Then obviously correct socket is used. Ideally code would know which socket needs to use before trying to create it. I'll have to look more deeply into the code how big rewrite it will be (and I'd prefer to have some ping tests written before changing it unless the change is trivial). And at least the warning could print whether the error is on IPv4 or on IPv6 to be at least a less confusing.

**Comment by floppym** [comment] 2020-09-02 21:25
I would guess that the desired outcome is to run `ping github.com` on a kernel with IPv6 disabled without seeing a warning message.

It is unlikely that a user who has disabled IPv6 support in the kernel would care that `ping` is unable to create an IPv6 socket.

**Comment by Whissi** [comment] 2020-09-02 21:42
...and keep in mind that github.com doesn't return any `AAAA` record at all. :)

**Comment by klynastor** [comment] 2020-11-25 05:29
This broke nagios on me, since nagios expects no warnings sent to stderr. Here's a quick patch.

`--- iputils-s20200821/ping/ping.c.bak   2020-11-25 00:22:54.000000000 -0500
+++ iputils-s20200821/ping/ping.c       2020-11-25 00:23:13.000000000 -0500
@@ -150,8 +150,8 @@
                /* Report error related to disabled IPv6 only when IPv6 also failed or in
                 * verbose mode. Report other errors always.
                 */
-               if ((errno == EAFNOSUPPORT && family == AF_INET6) ||
-                   rts->opt_verbose || requisite)
+               if ((errno == EAFNOSUPPORT && family == AF_INET6 && requisite) ||
+                   rts->opt_verbose)
                        error(0, errno, "socket");
                if (requisite)
                        exit(2);
`

**Comment by clayne** [comment] 2021-02-04 19:00
This is absolutely a regression. If a user pings a destination on an IPv4 only host, they should not suddenly be seeing a new warning just because `socket(AF_INET6, SOCK_DGRAM, IPPROTO_ICMPV6)` failed.

```
clayne@dorian:~ $ sudo strace ping -c1 192.168.1.1
[...]
socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP) = -1 EACCES (Permission denied)
socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = 3
socket(AF_INET6, SOCK_DGRAM, IPPROTO_ICMPV6) = -1 EAFNOSUPPORT (Address family not supported by protocol)
write(2, "ping: ", 6ping: )                   = 6
write(2, "socket", 6socket)                   = 6
write(2, ": Address family not supported b"..., 42: Address family not supported by protocol) = 42
write(2, "\n", 1
)                       = 1
```

This is the commit that first introduced this behavior based on a bisect:

```
904cdb6dc9bd511847e31689873f9c57172f6b8d is the first bad commit
commit 904cdb6dc9bd511847e31689873f9c57172f6b8d
Author: Sami Kerola <kerolasa@iki.fi>
Date:   Sat Nov 30 19:14:39 2019 +0000

    ping: AF_INET6 is address family not socket type [lgtm scan]
    
    The lgtm scan gave rather strange warning 'Comparison is always false
    because socktype <= 3.' at this point in code.  Looking a little bit closer
    to issue I realized wrong variable was compared.  This seems to have slipped
    into ping five releases ago.
    
    Broken-since: d141cb6e4ee3388f0508afa0f6368aaa1236778c
    Signed-off-by: Sami Kerola <kerolasa@iki.fi>

 ping/ping.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
bisect run success

clayne@dorian:/tmp/iputils/iputils ((904cdb6...)|BISECTING) $ git diff -u 904cdb6dc9bd511847e31689873f9c57172f6b8d~1
diff --git a/ping/ping.c b/ping/ping.c
index 8d15422..bcb88a8 100644
--- a/ping/ping.c
+++ b/ping/ping.c
@@ -149,7 +149,7 @@ static void create_socket(struct ping_rts *rts, socket_st *sock, int family,
                /* Report error related to disabled IPv6 only when IPv6 also failed or in
                 * verbose mode. Report other errors always.
                 */
-               if ((errno == EAFNOSUPPORT && socktype == AF_INET6) ||
+               if ((errno == EAFNOSUPPORT && family == AF_INET6) ||
                    rts->opt_verbose || requisite)
                        error(0, errno, "socket");
                if (requisite)
```

Presumably what happened here is that once the right variable was used this warning started being emitted in cases where AF_INET6 is not supported and nobody caught this because either the committers or build infrastructure is entirely dual-stack? However, it seems like the change above is merely a red herring and merely made the check start working correctly. IMO, the real issue started back in 9fd870a4bac0b8b2070c38452f378ef1eb7d460a once the conditional itself was changed.

cc @pavlix @kerolasa

**Comment by pevik** [comment] 2021-02-04 20:45
@lekto @clayne Could you please share your environment? I'm able to reproduce the problem with `ping -6 github.com` on kernel without IPv6 support (which is correct behavior), but with just `ping github.com` I get both `sock4.fd` and `sock6.fd` as valid sockets.
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1; sysctl -w net.ipv6.conf.default.disable_ipv6=1 # disable IPv6
./builddir/ping/ping -c1 -v github.com
PING github.com (140.82.121.3) 56(84) bytes of data.
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=1 ttl=48 time=16.6 ms
```

**Comment by lekto** [comment] 2021-02-06 06:55
Both my PC and my router: Gentoo ~amd64 (unstable), gentoo-sources-5.10.12 configured from scratch by me and iputils-20210202. In attachment is build log from iputils.

[build.log](https://github.com/iputils/iputils/files/5936402/build.log)

**Comment by Piraty** [comment] 2021-02-15 08:22
```
$ cat /proc/cmdline
<...> ipv6.disable=1
$ iputils-ping -c1 9.9.9.9
iputils-ping: socket: Address family not supported by protocol
PING 9.9.9.9 (9.9.9.9) 56(84) bytes of data.
64 bytes from 9.9.9.9: icmp_seq=1 ttl=55 time=13.7 ms
<...>
```

**Comment by pevik** [comment] 2021-02-15 10:27
Thanks a lot for a reproducer. I tried to disable with `sysctl -w net.ipv6.conf.all.disable_ipv6=1; sysctl -w net.ipv6.conf.default.disable_ipv6=1` which is not obviously enough (full disable on kernel cmdline is needed).
I'm busy with other tasks but try to have look into this soon.

**Comment by imThief** [comment] 2021-03-06 13:54
Hello!
I am experiencing same problem, ipv6 is not disabled - its not supported completely (CONFIG_IPV6 is not set, kernel doesn't know an AF_INET6 socket type) and commit with "if ((errno == EAFNOSUPPORT && family == AF_INET6)" is already in... Can you help?

my kernel is 5.4.97-gentoo-x86_64
[I] net-misc/iputils 20200821-r2(04:16:50 PM 02/23/2021)(arping filecaps nls ssl -caps -clockdiff -doc -gcrypt -idn -ipv6 -libressl -nettle -rarpd -rdisc -static -tftpd -tracepath -traceroute6)

Thanks!

**Comment by Vaevictusnet** [comment] 2021-04-27 13:01
So, to avoid the warning, any system with ipv6 disabled (for security reasons, for example) will have patch and recompile all systems that previously used ping for monitoring.  my nagios blew up.

**Comment by Vaevictusnet** [comment] 2021-04-27 14:17
looks like the nagios piece does ignore the -4 flag as well.

**Comment by pevik** [comment] 2021-04-27 14:33
I'm sorry, I have it on my TODO list, but have no idea when I get time for it.

**Comment by Vaevictusnet** [comment] 2021-04-28 13:09
In my use case, it's fine, nagios users are better suited to be using
check_icmp rather than the check_ping (wrapper) script. There may be
something that can be done on the nagios side, to force the -4 flag, but
i'm unsure how that would work with backwards compatibility and some other
things.

**Comment by pevik** [comment] 2021-04-28 20:24
>... There may be something that can be done on the nagios side, to force the -4 flag, but i'm unsure how that would work with backwards compatibility and some other things.

According to parameters in [check_ping doc](https://www.monitoring-plugins.org/doc/man/check_ping.html) is implemented in C: [check_ping.c](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_ping.c).
Because there are also other third party implementations: [perl](https://exchange.nagios.org/directory/Plugins/Network-Protocols/ICMP/check_ping-2Epl/details) and [shell](https://github.com/litzinetz-de/check_ping.sh/blob/master/check_ping.sh).

The official C implementation detects supported command, in my case `config.h` has
```
/* path and args for ICMPv6 ping command */
#define PING6_COMMAND "/usr/bin/ping6 -n -U -w %d -c %d %s"

/* Define if packet count must precede host */
#define PING6_PACKETS_FIRST 1

/* path and args for ICMP ping command */
#define PING_COMMAND "/usr/bin/ping -n -U -w %d -c %d %s"

/* Define if ping has its own timeout option that should be set */
#define PING_HAS_TIMEOUT 1

/* Define if packet count must precede host */
#define PING_PACKETS_FIRST 1
```
=> no `-4` or `-6` defined. And I suppose Nagios also supports [FreeBSD ping](https://www.freebsd.org/cgi/man.cgi?ping(8)), which does not have these switches.
If you're patient enough, we'll fix this issue.

**Comment by redtux** [comment] 2021-06-08 19:24
I am having the same issue as @lekto with `iputils-ping` 3:20210202-1 on Ubuntu 21.04 hirsute (rpi4/aarch64) and IPv6 disabled (via kernel parameter `ipv6.disable=1`).

```
ping -V
ping from iputils 20210202

ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 192.168.xxx.xxx/24 brd 192.168.xxx.255 scope global dynamic eth0
       valid_lft 77396sec preferred_lft 77396sec

uname -r
5.11.0-1009-raspi
```

**Comment by Ulenrich** [comment] 2021-06-21 10:56
The command has no effect if ipv6 is disabled in the kernel: 
> sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl: cannot stat /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory

**Comment by ruyrybeyro** [comment] 2021-08-14 06:22
Having issues in Debian 11, as @redtux , IPv6 disabled via kernel parameter:

    # ping -V
    ping from iputils 20210202 
    # ping 6.6.6.6
   ping: socket: Address family not supported by protocol
   PING 6.6.6.6 (6.6.6.6) 56(84) bytes of data.

**Comment by takenek** [comment] 2021-09-11 16:19
Same here on debian 11.

root@smokeping:~# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-5.10.0-8-amd64 root=/dev/mapper/smokeping--vg-root ro ipv6.disable=1 quiet

root@smokeping:~# cat /etc/gai.conf
precedence ::ffff:0:0/96  100

root@smokeping:~# ping 8.8.8.8 -c 1
ping: socket: Address family not supported by protocol
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=113 time=1.2 ms

root@smokeping:~# dpkg -l |grep iputils-ping
ii  iputils-ping                   3:20210202-1                   amd64        Tools to test the reachability of network hosts

Besr Regards

**Comment by ac000** [comment] 2021-09-16 20:25
Just had a look at this (needed to boot with ipv6.disable=1 to reproduce the issue) and I arrived at the same patch by @klynastor 

> ```
> --- iputils-s20200821/ping/ping.c.bak   2020-11-25 00:22:54.000000000 -0500
> +++ iputils-s20200821/ping/ping.c       2020-11-25 00:23:13.000000000 -0500
> @@ -150,8 +150,8 @@
>                 /* Report error related to disabled IPv6 only when IPv6 also failed or in
>                  * verbose mode. Report other errors always.
>                  */
> -               if ((errno == EAFNOSUPPORT && family == AF_INET6) ||
> -                   rts->opt_verbose || requisite)
> +               if ((errno == EAFNOSUPPORT && family == AF_INET6 && requisite) ||
> +                   rts->opt_verbose)
>                         error(0, errno, "socket");
>                 if (requisite)
>                         exit(2);
> ```

You need to make _requisite_ part of the first half of the logic, so that other than if verbose is set we only print the socket error if we failed on IPv6 _and_ failed on IPv4. Or we are only trying and failed on IPv6.

**Comment by pevik** [comment] 2021-09-16 22:43
Fix is ready, anybody feel free to test and put your `Reviewed-by: Your Name <your@email>` tag.
I'm sorry it took me one year to fix this simple issue.

**Comment by imThief** [comment] 2021-09-16 23:36
I'm sorry, is this commit already in master branch? Can i just clone it, compile and test or should i choose some side branch? Work with git unfortunately not among my virtues ...

**Comment by ac000** [comment] 2021-09-17 00:43
@imThief

If you already have this repository checked out, you can simply pull this change over with

```
git pull https://github.com/pevik/iputils/ ping/gh#293
```

**Comment by pevik** [comment] 2021-09-19 19:05
@imThief FYI fix merged.

**Closed** 2021-09-19 19:04 UTC
Labels: bug, reproducer
