### ISSUE TITLE
ping no latency but name resolve timeout

### ISSUE THREAD

**Issue by Sora233** [iputils/iputils#461] opened 2023-05-04 10:06 UTC
```
$ ./ping -D -v baidu.com
./ping: sock4.fd: 3 (socktype: SOCK_DGRAM), sock6.fd: 4 (socktype: SOCK_DGRAM), hints.ai_family: AF_UNSPEC

ai->ai_family: AF_INET, ai->ai_canonname: 'baidu.com'
PING baidu.com (110.242.68.66) 56(84) bytes of data.
[1683193586.191093] 64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=1 ttl=51 time=48.9 ms
[1683193587.192538] 64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=2 ttl=51 time=49.2 ms
[1683193603.200929] 64 bytes from 110.242.68.66: icmp_seq=3 ttl=51 time=49.3 ms
[1683193613.266337] 64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=4 ttl=51 time=49.0 ms
[1683193628.321308] 64 bytes from 110.242.68.66: icmp_seq=5 ttl=51 time=49.1 ms
[1683193628.377484] 64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=6 ttl=51 time=48.9 ms
[1683193639.386561] 64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=7 ttl=51 time=49.0 ms
[1683193639.448621] 64 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=8 ttl=51 time=53.3 ms
```

there is a lag between some icmp_seq, not the actual icmp latency.

with strace log I find it is a problem about dns, ip 192.168.10.1 is my eth router.

```
17:50:42 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 5
17:50:42 setsockopt(5, SOL_IP, IP_RECVERR, [1], 4) = 0
17:50:42 connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.10.1")}, 16) = 0
17:50:42 ppoll([{fd=5, events=POLLOUT}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=5, revents=POLLOUT}], left {tv_sec=0, tv_nsec=0})
17:50:42 sendto(5, "\361a\1\0\0\1\0\0\0\0\0\0\00266\00268\003242\003110\7in-ad"..., 44, MSG_NOSIGNAL, NULL, 0) = 44
17:50:42 ppoll([{fd=5, events=POLLIN}], 1, {tv_sec=5, tv_nsec=0}, NULL, 0) = 0 (Timeout)
17:50:47 socket(AF_INET6, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 7
```

and  it seems ok after I add flag `-n` to disable dns name resolve.

```
$ ./ping -D -n -v baidu.com
./ping: sock4.fd: 3 (socktype: SOCK_DGRAM), sock6.fd: 4 (socktype: SOCK_DGRAM), hints.ai_family: AF_UNSPEC

ai->ai_family: AF_INET, ai->ai_canonname: 'baidu.com'
PING baidu.com (39.156.66.10) 56(84) bytes of data.
[1683194392.011520] 64 bytes from 39.156.66.10: icmp_seq=1 ttl=53 time=38.8 ms
[1683194393.012968] 64 bytes from 39.156.66.10: icmp_seq=2 ttl=53 time=39.2 ms
[1683194394.014221] 64 bytes from 39.156.66.10: icmp_seq=3 ttl=53 time=38.9 ms
[1683194395.015645] 64 bytes from 39.156.66.10: icmp_seq=4 ttl=53 time=39.1 ms
[1683194396.018399] 64 bytes from 39.156.66.10: icmp_seq=5 ttl=53 time=40.6 ms
[1683194397.019834] 64 bytes from 39.156.66.10: icmp_seq=6 ttl=53 time=40.3 ms
[1683194398.020272] 64 bytes from 39.156.66.10: icmp_seq=7 ttl=53 time=39.3 ms
[1683194399.021706] 64 bytes from 39.156.66.10: icmp_seq=8 ttl=53 time=39.3 ms
[1683194400.023458] 64 bytes from 39.156.66.10: icmp_seq=9 ttl=53 time=39.6 ms
[1683194401.025035] 64 bytes from 39.156.66.10: icmp_seq=10 ttl=53 time=39.3 ms
```

Also it seems  my router is good as I can run `dig @192.168.10.1 baidu.com`  1000k times and response time is all under 10ms

info:
Kernel: Linux raspberrypi 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux

iputils version: found on `ping from iputils 20210202` and  also test on master

os release:
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

**Comment by pevik** [comment] 2023-05-05 00:16
baidu.com has 2 A records:
```
dig +nocmd +noall +answer baidu.com
baidu.com.		418	IN	A	110.242.68.66
baidu.com.		418	IN	A	39.156.66.10
```

That's the only difference I can see, I have no idea why is resolving so slow.

Also, it looks like you run `ping` with `strace --absolute-timestamps`. If you run it as `strace -r -T`, it'd be more clear where that 5 sec was spent. Note, you can also run `ltrace -r -T`, but I don't think it help us much.

**Comment by Sora233** [comment] 2023-05-05 06:11
I run it as `strace -r -T ./ping -C baidu.com` with output:
```
     0.000191 write(1, "64 bytes from 110.242.68.66 (110"..., 7764 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=16 ttl=51 time=41.0 ms
) = 77 <0.000046>
     0.000140 ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=0, tv_nsec=951000000}, NULL, 0) = 0 (Timeout) <0.952027>
     0.952164 sendto(3, "\10\0t\262\377\377\0\21\250\234Td\0\0\0\0\306h\1\0\0\0\0\0\20\21\22\23\24\25\26\27"..., 64, 0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("110.242.68.66")}, 16) = 64 <0.000088>
     0.000291 recvmsg(3, {msg_name={sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("110.242.68.66")}, msg_namelen=128->16, msg_iov=[{iov_base="\0\0|\254\0\6\0\21\250\234Td\0\0\0\0\306h\1\0\0\0\0\0\20\21\22\23\24\25\26\27"..., iov_len=192}], msg_iovlen=1, msg_control=[{cmsg_len=32, cmsg_level=SOL_SOCKET, cmsg_type=SO_TIMESTAMP_OLD, cmsg_data={tv_sec=1683266728, tv_usec=133114}}, {cmsg_len=20, cmsg_level=SOL_IP, cmsg_type=IP_TTL, cmsg_data=[51]}], msg_controllen=56, msg_flags=0}, 0) = 64 <0.040485>
     0.040702 newfstatat(AT_FDCWD, "/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=50, ...}, 0) = 0 <0.000054>
     0.000165 openat(AT_FDCWD, "/etc/hosts", O_RDONLY|O_CLOEXEC) = 5 <0.000064>
     0.000165 lseek(5, 0, SEEK_CUR)     = 0 <0.000048>
     0.000125 fstat(5, {st_mode=S_IFREG|0644, st_size=138, ...}) = 0 <0.000045>
     0.000150 read(5, "127.0.0.1\tlocalhost\n# ::1\t\tlocal"..., 4096) = 138 <0.000051>
     0.000151 lseek(5, 0, SEEK_CUR)     = 138 <0.000070>
     0.000148 read(5, "", 4096)         = 0 <0.000040>
     0.000152 close(5)                  = 0 <0.000045>
     0.000138 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 5 <0.000053>
     0.000130 setsockopt(5, SOL_IP, IP_RECVERR, [1], 4) = 0 <0.000041>
     0.000129 connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.10.1")}, 16) = 0 <0.000057>
     0.000194 ppoll([{fd=5, events=POLLOUT}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=5, revents=POLLOUT}], left {tv_sec=0, tv_nsec=0}) <0.000042>
     0.000162 sendto(5, "\236\226\1\0\0\1\0\0\0\0\0\0\00266\00268\003242\003110\7in-ad"..., 44, MSG_NOSIGNAL, NULL, 0) = 44 <0.000119>
     0.000259 ppoll([{fd=5, events=POLLIN}], 1, {tv_sec=5, tv_nsec=0}, NULL, 0) = 1 ([{fd=5, revents=POLLIN}], left {tv_sec=4, tv_nsec=991213809}) <0.008828>
     0.008942 ioctl(5, FIONREAD, [149]) = 0 <0.000031>
     0.000108 recvfrom(5, "\236\226\201\203\0\1\0\0\0\1\0\0\00266\00268\003242\003110\7in-ad"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.10.1")}, [28->16]) = 149 <0.000034>
     0.000174 close(5)                  = 0 <0.000074>
     0.000197 write(1, "64 bytes from 110.242.68.66 (110"..., 7764 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=17 ttl=51 time=40.8 ms
) = 77 <0.000045>
     0.000144 ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=0, tv_nsec=948000000}, NULL, 0) = 0 (Timeout) <0.949026>
     0.949167 sendto(3, "\10\0i\252\377\377\0\22\251\234Td\0\0\0\0\320o\1\0\0\0\0\0\20\21\22\23\24\25\26\27"..., 64, 0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("110.242.68.66")}, 16) = 64 <0.000091>
     0.000301 recvmsg(3, {msg_name={sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("110.242.68.66")}, msg_namelen=128->16, msg_iov=[{iov_base="\0\0q\244\0\6\0\22\251\234Td\0\0\0\0\320o\1\0\0\0\0\0\20\21\22\23\24\25\26\27"..., iov_len=192}], msg_iovlen=1, msg_control=[{cmsg_len=32, cmsg_level=SOL_SOCKET, cmsg_type=SO_TIMESTAMP_OLD, cmsg_data={tv_sec=1683266729, tv_usec=135061}}, {cmsg_len=20, cmsg_level=SOL_IP, cmsg_type=IP_TTL, cmsg_data=[51]}], msg_controllen=56, msg_flags=0}, 0) = 64 <0.040611>
     0.040808 newfstatat(AT_FDCWD, "/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=50, ...}, 0) = 0 <0.000086>
     0.000194 openat(AT_FDCWD, "/etc/hosts", O_RDONLY|O_CLOEXEC) = 5 <0.000056>
     0.000146 lseek(5, 0, SEEK_CUR)     = 0 <0.000034>
     0.000115 fstat(5, {st_mode=S_IFREG|0644, st_size=138, ...}) = 0 <0.000035>
     0.000116 read(5, "127.0.0.1\tlocalhost\n# ::1\t\tlocal"..., 4096) = 138 <0.000042>
     0.000128 lseek(5, 0, SEEK_CUR)     = 138 <0.000034>
     0.000101 read(5, "", 4096)         = 0 <0.000037>
     0.000129 close(5)                  = 0 <0.000045>
     0.000149 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 5 <0.000056>
     0.000137 setsockopt(5, SOL_IP, IP_RECVERR, [1], 4) = 0 <0.000067>
     0.000174 connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.10.1")}, 16) = 0 <0.000084>
     0.000186 ppoll([{fd=5, events=POLLOUT}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=5, revents=POLLOUT}], left {tv_sec=0, tv_nsec=0}) <0.000053>
     0.000155 sendto(5, "ep\1\0\0\1\0\0\0\0\0\0\00266\00268\003242\003110\7in-ad"..., 44, MSG_NOSIGNAL, NULL, 0) = 44 <0.000119>
     0.000252 ppoll([{fd=5, events=POLLIN}], 1, {tv_sec=5, tv_nsec=0}, NULL, 0) = 0 (Timeout) <5.005077>
     5.005215 ppoll([{fd=5, events=POLLOUT}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=5, revents=POLLOUT}], left {tv_sec=0, tv_nsec=0}) <0.000032>
     0.000156 sendto(5, "ep\1\0\0\1\0\0\0\0\0\0\00266\00268\003242\003110\7in-ad"..., 44, MSG_NOSIGNAL, NULL, 0) = 44 <0.000074>
     0.000214 ppoll([{fd=5, events=POLLIN}], 1, {tv_sec=5, tv_nsec=0}, NULL, 0) = 1 ([{fd=5, revents=POLLIN}], left {tv_sec=4, tv_nsec=406108336}) <0.593949>
     0.594111 ioctl(5, FIONREAD, [44])  = 0 <0.000034>
     0.000137 recvfrom(5, "ep\201\200\0\1\0\0\0\0\0\0\00266\00268\003242\003110\7in-ad"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.10.1")}, [28->16]) = 44 <0.000039>
     0.000218 close(5)                  = 0 <0.000084>
     0.000212 write(1, "64 bytes from 110.242.68.66 (110"..., 7764 bytes from 110.242.68.66 (110.242.68.66): icmp_seq=18 ttl=51 time=40.9 ms
) = 77 <0.000051>
     0.000161 sendto(3, "\10\0\224\327\377\377\0\23\256\234Td\0\0\0\0\226A\v\0\0\0\0\0\20\21\22\23\24\25\26\27"..., 64, 0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("110.242.68.66")}, 16) = 64 <0.000140>
```
And `-C` doesn't help.

**Comment by pevik** [comment] 2023-05-05 08:55
Indeed one of the `sendto()` takes long time. Unfortunately I'm not able to tell why.

```
0.000156 sendto(5, "ep\1\0\0\1\0\0\0\0\0\0\00266\00268\003242\003110\7in-ad"..., 44, MSG_NOSIGNAL, NULL, 0) = 44 <0.000074>
0.000214 ppoll([{fd=5, events=POLLIN}], 1, {tv_sec=5, tv_nsec=0}, NULL, 0) = 1 ([{fd=5, revents=POLLIN}], left {tv_sec=4, tv_nsec=406108336}) <0.593949>
```
You could try to test
* different nameserver (google's `8.8.8.8`)
* different ping implementations [fping](https://fping.org/), ping from [busybox](https://git.busybox.net/busybox/tree/networking/ping.c) (which uses raw socket)
* try `ping` from iputtils to force raw socket (with `sysctl -w net.ipv4.ping_group_range='1 0'`)

And the latest result is to write to https://superuser.com/ or https://unix.stackexchange.com/ (IMHO the problem is in your network, because I ping baidu.com normally).

**Closed** 2023-05-06 02:36 UTC
