### ISSUE TITLE
Release procedure 

### ISSUE THREAD

**Issue by pevik** [iputils/iputils#234] opened 2019-11-26 14:12 UTC
It'd be nice to formalize release procedure 
continue discussion from https://github.com/iputils/iputils/pull/231#issuecomment-558218096:
_How about starting the release by announcing incoming release using bug ticket that tells when the release will happen, and stays open for a bit afterwards to capture fallout. The rc releases are a bit problematic. They do not tend to get more testers than the usual community. Or that's at least my former experience, and I remain doubtful if they are worthwhile doing at all._

**Comment by pevik** [comment] 2019-11-26 14:17
Agree with the ticket (I'm used from other project to communicate via mailing lists, github issues are good equivalent). Maybe we could even use github milestones. Although ticket with listed required tickets to be solved would be enough for me.

What I wanted by RC is to inform the community (at least distro packagers) to do basic testing.
We don't have to add archives, but I'd prefer to have tag for RC to be clear what is being tested.

Other question is whether we should have some time based release or irregular. (e.g. in LTP we freeze git after 4 months of development, do a bit of testing and release).

**Comment by nmeyerhans** [comment] 2019-11-26 14:47
> What I wanted by RC is to inform the community (at least distro packagers) to do basic testing.
> We don't have to add archives, but I'd prefer to have tag for RC to be clear what is being tested.

I'm happy to upload RC (or other non-release snapshots) to Debian unstable and OpenWRT.

> Other question is whether we should have some time based release or irregular. (e.g. in LTP we freeze git after 4 months of development, do a bit of testing and release).

IMO, because feature development isn't that fast, time-based releases aren't that helpful. What I might suggest is something of a compromise. As-needed releases, but with a goal of not having a feature or bugfix unreleased for more than 4 months (arbitrarily chosen; feel free to adjust). That way you ensure that changes don't languish, while also avoiding releases just for the sake of adhering to an arbitrary schedule.

One change that I'd like to request is the reintroduction of a CHANGELOG or release notes or something similar. The git history is appropriate for developers, but not for users. The changelog should describe changes in functionality that impact users of the software, without requiring familiarity with git or the implementation details of the software. One way that the changelog might be maintained in an ongoing way is the ask contributors to provide a changelog entry as part of a PR. This could be done either in the PR summary, or in a commit to a changelog file.

**Comment by pevik** [comment] 2019-11-26 16:18
Agree on combined *as-needed* releases, no longer than 4 months.
Changelog vs. release notes: are release notes I did for latest release enough? https://github.com/iputils/iputils/releases/tag/s20190709
I think it should be written by maintainers (we need to understand code which we merge and it's impact).

**Comment by nmeyerhans** [comment] 2019-11-27 14:52
Yes, the release notes for the 20190709 snapshot are basically what I have in mind. Would like to see them in a format that can be included with the installation. It Debian, it is standard to have upstream changelogs available in /usr/share/doc/<pkg>/changelog. Having a consistent location for upstream changelogs is immensely helpful when chasing regressions.

It may work to simply maintain a changelog.md file in the repository that is in a format compatible with GitHub releases.  When the time comes to make a release, simply copy & paste the relevant notes into the GitHub form.

**Comment by kerolasa** [comment] 2019-11-27 19:34
Aiming to release in 4 month intervals sounds good to me. If release are needed more often then they need to be done.

Maximum frequency should be once per day. If a release is found to be so bad that another is needed immediately tell in release notes no-one should use it and try again later. If we really mess up a release so bad that another release is needed immediately then rushing is wrong reaction. To be honest if a release goes totally to south I think it's best to reserve few days or a week to sort out issue(s).

**Comment by pevik** [comment] 2019-11-28 08:55
@nmeyerhans understand a reason (I'm also a Debian user, I know Debian policy), but I'd prefer to have release notes just online and let distros to copy paste the content.

**Comment by nmeyerhans** [comment] 2019-11-28 15:54
The problem with that is that it distributes something that should be centralized. I *can* do what you describe, for the Debian packages, but it only benefits Debian users. That's not the only user community that will appreciate offline access to the changelog.

Also, AFAIK, there is no way to get the raw markdown source for the github release notes. That means I, and anybody else interested in maintaining a changelog for offline use, must carefully copy & paste from a browser and convert back to some text format by hand. That's tedious, error-prone, and generally quite unpleasant.

**Comment by kerolasa** [comment] 2019-11-28 18:58
Does anyone know if there is some system to publish across distributions change logs? Integrating change log with Anitya[1] in my mind would be ideal. But quickly looking I don't see support for that. If structured text that can be reused across distributions is found then I do not have objections to start maintaining them. Unpleasant thing is that no--one, including me, likes this sort of tedious text tinkering, so the only reason why I would do these is to avoid everyone duplicating the effort.

[1] https://release-monitoring.org/project/1395/

**Comment by pevik** [comment] 2019-11-29 07:41
@nmeyerhans I'm not against chagelog, I just wish if it wasn't part of git, but part of tarball. The extreme of this is glibc way (maintaining changelog for each commit). The downside of it adding changelog into git is growing git size with things not needed. Would it work for you?

This the same as whole project using github. I'd be much happier if project used mailing list and normal web pages.

**Comment by pevik** [comment] 2019-11-29 07:46
@kerolasa I've noticed Buildroot distro uses https://release-monitoring.org project (https://release-monitoring.org/distro/Buildroot/?page=16), but IMHO it's goal is different (they target to end users, not projects), so I'm not surprise they don't help us with it.

**Comment by kerolasa** [comment] 2019-12-07 17:23
@pevik just to let you know, I don't have any pending changes to iputils right now so feel free to move forward with the release. The https://github.com/iputils/iputils/pull/229 is perhaps best to leave out from next release.

**Comment by pevik** [comment] 2019-12-08 10:40
@kerolasa thx for info. Agree #229 should be left out. Before releasing I'd like to finish release procedure changes. 

Looking at some IMHO good projects:
* [buildroot](https://buildroot.org/news.html) has [CHANGES](https://git.busybox.net/buildroot/tree/CHANGES) file, containing all the changes, but it's rather brief and without any markup being used (both IMHO good) and it's [online].(https://git.buildroot.net/buildroot/plain/CHANGES?id=2019.02.7).
* [util-linux](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.34/), which is IMHO very good user space project: it has 1) [changelog](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.34/v2.34-rc1-ChangeLog) which is generated by git 2) [release notes](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.34/v2.34-ReleaseNotes). None of them is part of released tarballs, but it available online and downloadable.

We could follow buildroot way (have brief file in git, which is also downloadable). But besides I'd really try to avoid including git, I don't like there are all changes in single file.
Other possible way for us: 1) include release notes as a file (e.g. `RELEASE_NOTES.s20190709`) in https://github.com/iputils/iputils/releases with the same content of actual text, but markdown being striped and add its hash into `sha256sum.asc`. 2) We could also add this file into tarball 3) + also add git generated file `CHANGELOG.s20190709`, only into tarball.

@nmeyerhans @kerolasa what would you prefer?

**Comment by kerolasa** [comment] 2020-01-02 18:51
I don't have preference. @pevik feel free to choose some way to release, and it could be nice to get release done before spring.

**Comment by wtip** [comment] 2020-08-01 02:41
What's the holdup for getting a new release out? A package I use that makes use of `arping` for VIP failover stopped working on Ubuntu 20.04 because of a bug that was fixed with this commit https://github.com/iputils/iputils/commit/68f12fc4a0dbef4ae4c404da24040d22c5a14339 
It would be nice if I could file a ubuntu bugreport to get the package updated but you don't have an upstream release with this fix.

**Comment by pevik** [comment] 2020-08-01 04:43
> What's the holdup for getting a new release out?

@kerolasa or me finding a time. I'm sorry we should have released long time ago. I wanted first to fix https://github.com/iputils/iputils/pull/256, but maybe we should release without it.

**Comment by pevik** [comment] 2020-08-01 07:06
> A package I use that makes use of `arping` for VIP failover stopped working on Ubuntu 20.04 because of a bug that was fixed with this commit [68f12fc](https://github.com/iputils/iputils/commit/68f12fc4a0dbef4ae4c404da24040d22c5a14339)
> It would be nice if I could file a ubuntu bugreport to get the package updated but you don't have an upstream release with this fix.

Could you report it in Ubuntu? Package maintainer will backport it (quick fix for now) and post a link to bugreport here?

**Comment by kerolasa** [comment] 2020-08-01 08:01
> What's the holdup for getting a new release out?

https://github.com/iputils/iputils/pull/255#issuecomment-612859728

**Comment by nmeyerhans** [comment] 2020-08-01 17:03
> > What's the holdup for getting a new release out?
> 
> [#255 (comment)](https://github.com/iputils/iputils/pull/255#issuecomment-612859728)

IMO it would be reasonable to release without #255. If it was a regression from a previous release, then it'd be worth blocking, but since it's a new feature, leaving it out from a new release won't break anybody.

A new release will let me update iputils in Debian's unstable and testing branches, which will get built on a number of different architectures and tested in different use cases. That'll help uncover any new bugs or regressions, which will ultimately lead to more bugs being squashed.

Release early, release often, etc.

**Comment by pevik** [comment] 2020-08-01 19:38
@nmeyerhans Agree. I'll try to prepare release ASAP. Hope next release will be earlier.

**Comment by pevik** [comment] 2020-08-03 12:42
@nmeyerhans I'm suggesting some changes in release procedure in https://github.com/iputils/iputils/pull/283, e.g. adding `CHANGES` file.

**Closed** 2020-09-18 06:33 UTC
