### ISSUE TITLE
arping can not set timeout of numbers with decimal point

### ISSUE THREAD

**Issue by kevinzs2048** [iputils/iputils#267] opened 2020-05-15 01:48 UTC
\#arping -V
arping from iputils s20190709

\#arping -A -c 3 -w 4.5 -I br-ex 10.101.96.101
arping: invalid argument: '4.5'

**Comment by pevik** [comment] 2020-05-15 07:10
This is caused by locales, it needs similar fix as d865d4c468965bbff1b9d6b912eee44ade52967d.

**Comment by pevik** [comment] 2020-05-15 07:18
No, I was wrong `-w` expects int. The same is for ping. And the bug title is wrong: `4.5` is not decimal.

**Comment by kevin-zhaoshuai** [comment] 2020-05-15 07:27
@pevik Thanks! But I saw from the version 2016 arping, user can set the -w with numbers with decimal, such as -w 2.5

**Comment by pevik** [comment] 2020-05-15 08:04
I'm sorry I was wrong (confused integer number with decimal number, my bad English).

But even then `-w` is handled with `int`
https://github.com/iputils/iputils/blob/s20160308/arping.c#L81
and thus converted in `atoi()`
https://github.com/iputils/iputils/blob/s20160308/arping.c#L1044
=> `4.5` was taken as `4`. Only later @kerolasa added check for int, which is IMHO correct, than pretending we handle decimal instead of int.

**Comment by pevik** [comment] 2020-08-10 16:23
@kevinzs2048 feel free to comment on #290.

**Comment by pevik** [comment] 2021-09-19 21:51
I'm closing the bug as it's invalid. But we could certainly do 2 things: 1) note in man page that only natural numbers are expected, 2) improve error message to print expected input range.

**Closed by pevik** 2021-09-19 21:51 UTC
